
CREATE TABLE country (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         continent VARCHAR(255) NOT NULL
);


CREATE TABLE author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        surname VARCHAR(255) NOT NULL,
                        country_id BIGINT,
                        FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE SET NULL
);


CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      category VARCHAR(255) NOT NULL, -- Assuming BookCategory is a String enum
                      author_id BIGINT,
                      FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL
);


CREATE TABLE book_copy (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           book_id BIGINT NOT NULL,
                           is_loaned BOOLEAN NOT NULL DEFAULT FALSE,
                           FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);


CREATE TABLE book_history (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              category VARCHAR(255) NOT NULL, -- Assuming BookCategory is a String enum
                              author_id BIGINT,
                              FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE
);


CREATE TABLE shop_users (
                            username VARCHAR(255) PRIMARY KEY,
                            password VARCHAR(255) NOT NULL,
                            name VARCHAR(255) NOT NULL,
                            surname VARCHAR(255) NOT NULL,
                            role VARCHAR(255) NOT NULL, -- Assuming Role is a String enum
                            is_account_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
                            is_account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
                            is_credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
                            is_enabled BOOLEAN NOT NULL DEFAULT TRUE
);





INSERT INTO shop_users (username, password, name, surname, role)
VALUES (
           'li',
           '$2a$10$s6a4wIH30XUqHYg6YcZGS.WshLLVeXTmEiKw4yDyLtQNkhpuICeVy',
           'Snezana',
           'Koleva',
           'ROLE_LIBRARIAN'
       );

CREATE TABLE book_readers (
                              book_id BIGINT NOT NULL,
                              user_username VARCHAR(255) NOT NULL,
                              PRIMARY KEY (book_id, user_username),
                              FOREIGN KEY (book_id) REFERENCES book(id),
                              FOREIGN KEY (user_username) REFERENCES shop_users(username)
);
